# Generated by Django 5.2 on 2025-05-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("positions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="position",
            options={
                "verbose_name": "Специализация",
                "verbose_name_plural": "Специализации",
            },
        ),
        migrations.RemoveField(
            model_name="grade",
            name="description",
        ),
        migrations.AddField(
            model_name="grade",
            name="positions",
            field=models.TextField(blank=True, verbose_name="Должности"),
        ),
        migrations.AlterField(
            model_name="position",
            name="name",
            field=models.CharField(
                max_length=100, verbose_name="Название специализации"
            ),
        ),
    ]
