# Generated by Django 5.2 on 2025-05-05 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("positions", "0003_alter_grade_options_grade_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название параметра"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Параметр",
                "verbose_name_plural": "Параметры",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ParameterDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameter_descriptions",
                        to="positions.grade",
                        verbose_name="Грейд",
                    ),
                ),
                (
                    "parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="descriptions",
                        to="positions.parameter",
                        verbose_name="Параметр",
                    ),
                ),
            ],
            options={
                "verbose_name": "Описание параметра",
                "verbose_name_plural": "Описания параметров",
                "ordering": ["parameter__name", "grade__name"],
                "unique_together": {("parameter", "grade")},
            },
        ),
    ]
