# Generated by Django 5.2 on 2025-05-05 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("positions", "0004_parameter_parameterdescription"),
    ]

    operations = [
        migrations.AddField(
            model_name="parameter",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="positions.position",
                verbose_name="Специализация",
            ),
        ),
    ]
