# Generated by Django 5.2 on 2025-05-05 17:22

import django.db.models.deletion
from django.db import migrations, models

def remove_duplicates(apps, schema_editor):
    Position = apps.get_model('positions', 'Position')
    # Создаем словарь для хранения уникальных позиций
    unique_positions = {}
    
    # Собираем все позиции
    for position in Position.objects.all():
        if position.name not in unique_positions:
            unique_positions[position.name] = position
        else:
            # Если позиция с таким именем уже существует, удаляем дубликат
            position.delete()

class Migration(migrations.Migration):

    dependencies = [
        ("positions", "0005_parameter_position"),
    ]

    operations = [
        migrations.RunPython(remove_duplicates),
        migrations.AlterModelOptions(
            name="position",
            options={
                "ordering": ["name"],
                "verbose_name": "Специализация",
                "verbose_name_plural": "Специализации",
            },
        ),
        migrations.RemoveField(
            model_name="position",
            name="confirmation_points",
        ),
        migrations.RemoveField(
            model_name="position",
            name="grade",
        ),
        migrations.RemoveField(
            model_name="position",
            name="promotion_points",
        ),
        migrations.AlterField(
            model_name="position",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Название специализации"
            ),
        ),
        migrations.CreateModel(
            name="PositionGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "confirmation_points",
                    models.IntegerField(verbose_name="Подтверждающие баллы"),
                ),
                (
                    "promotion_points",
                    models.IntegerField(verbose_name="Повышающие баллы"),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="positions.grade",
                        verbose_name="Грейд",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="positions.position",
                        verbose_name="Специализация",
                    ),
                ),
            ],
            options={
                "verbose_name": "Специализация в грейде",
                "verbose_name_plural": "Специализации в грейдах",
                "ordering": ["position__name", "grade__name"],
                "unique_together": {("position", "grade")},
            },
        ),
    ]
