# Generated by Django 5.2 on 2025-05-05 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("positions", "0007_migrate_position_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст вопроса")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("technical", "Технический"),
                            ("behavioral", "Поведенческий"),
                            ("system_design", "Системный дизайн"),
                            ("problem_solving", "Решение задач"),
                            ("culture_fit", "Культурное соответствие"),
                        ],
                        max_length=20,
                        verbose_name="Категория вопроса",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Порядок")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="positions.grade",
                        verbose_name="Грейд",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="positions.position",
                        verbose_name="Специализация",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вопрос интервью",
                "verbose_name_plural": "Вопросы интервью",
                "ordering": ["position__name", "grade__order", "order"],
                "unique_together": {("text", "grade", "position")},
            },
        ),
    ]
