# Generated by Django 5.2 on 2025-05-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("positions", "0008_interviewquestion"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="interviewquestion",
            options={
                "ordering": ["position__name", "order"],
                "verbose_name": "Вопрос интервью",
                "verbose_name_plural": "Вопросы интервью",
            },
        ),
        migrations.AlterUniqueTogether(
            name="interviewquestion",
            unique_together={("text", "position")},
        ),
        migrations.AddField(
            model_name="interviewquestion",
            name="question_type",
            field=models.CharField(
                choices=[("question", "Вопрос"), ("test", "Тестовое")],
                default="question",
                max_length=20,
                verbose_name="Тип вопроса",
            ),
        ),
        migrations.AddField(
            model_name="interviewquestion",
            name="test_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single_choice", "Один ответ"),
                    ("multiple_choice", "Множественный ответ"),
                    ("open_ended", "Открытый вопрос"),
                    ("drag_drop", "Карточки (drag&drop)"),
                ],
                max_length=20,
                null=True,
                verbose_name="Тип тестового",
            ),
        ),
        migrations.RemoveField(
            model_name="interviewquestion",
            name="category",
        ),
        migrations.RemoveField(
            model_name="interviewquestion",
            name="grade",
        ),
    ]
