# Generated by Django 5.2 on 2025-05-06 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("positions", "0009_alter_interviewquestion_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScoreMatrix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название матрицы"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_matrices",
                        to="positions.position",
                    ),
                ),
            ],
            options={
                "verbose_name": "Матрица пересчета баллов",
                "verbose_name_plural": "Матрицы пересчета баллов",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScoreMatrixCell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Балл"
                    ),
                ),
                (
                    "matrix",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cells",
                        to="positions.scorematrix",
                    ),
                ),
                (
                    "parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="positions.parameter",
                        verbose_name="Параметр",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="positions.interviewquestion",
                        verbose_name="Вопрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ячейка матрицы",
                "verbose_name_plural": "Ячейки матрицы",
                "unique_together": {("matrix", "parameter", "question")},
            },
        ),
        migrations.CreateModel(
            name="ScoreMatrixSum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sum_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Сумма"
                    ),
                ),
                (
                    "is_row_sum",
                    models.BooleanField(default=True, verbose_name="Сумма по строке"),
                ),
                (
                    "matrix",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sums",
                        to="positions.scorematrix",
                    ),
                ),
                (
                    "parameter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="positions.parameter",
                        verbose_name="Параметр",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="positions.interviewquestion",
                        verbose_name="Вопрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сумма матрицы",
                "verbose_name_plural": "Суммы матрицы",
                "unique_together": {("matrix", "parameter", "question", "is_row_sum")},
            },
        ),
    ]
