# Generated by Django 5.2 on 2025-05-06 10:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("positions", "0011_alter_scorematrix_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "candidate_name",
                    models.CharField(max_length=255, verbose_name="ФИО кандидата"),
                ),
                (
                    "expected_salary",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Ожидаемая ЗП"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "current_grade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_interviews",
                        to="positions.grade",
                        verbose_name="Текущий грейд",
                    ),
                ),
                (
                    "expected_grade",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expected_interviews",
                        to="positions.grade",
                        verbose_name="Ожидаемый грейд",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="positions.position",
                        verbose_name="Специализация",
                    ),
                ),
            ],
            options={
                "verbose_name": "Интервью",
                "verbose_name_plural": "Интервью",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InterviewAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Балл",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Заметки")),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="positions.interview",
                        verbose_name="Интервью",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="positions.interviewquestion",
                        verbose_name="Вопрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ на вопрос",
                "verbose_name_plural": "Ответы на вопросы",
                "unique_together": {("interview", "question")},
            },
        ),
        migrations.CreateModel(
            name="InterviewResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Балл"
                    ),
                ),
                (
                    "interview",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="positions.interview",
                        verbose_name="Интервью",
                    ),
                ),
                (
                    "parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="positions.parameter",
                        verbose_name="Параметр",
                    ),
                ),
            ],
            options={
                "verbose_name": "Результат по параметру",
                "verbose_name_plural": "Результаты по параметрам",
                "unique_together": {("interview", "parameter")},
            },
        ),
    ]
