# Generated by Django 5.2 on 2025-05-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("positions", "0012_interview_interviewanswer_interviewresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активна"),
        ),
    ]
