# Generated by Django 5.2 on 2025-05-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("positions", "0013_position_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="grade",
            name="max_score",
            field=models.DecimalField(
                decimal_places=2,
                default=100,
                max_digits=5,
                verbose_name="Максимальный балл",
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="min_score",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Минимальный балл",
            ),
        ),
    ]
