# Generated by Django 5.2 on 2025-05-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("positions", "0014_grade_max_score_grade_min_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="general_notes",
            field=models.TextField(blank=True, verbose_name="Общие заметки"),
        ),
    ]
