# Generated by Django 5.0.2 on 2025-05-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("positions", "0017_candidate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidate",
            name="current_position",
        ),
        migrations.AddField(
            model_name="candidate",
            name="desired_position",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Желаемая должность"
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="resume",
            field=models.FileField(
                blank=True, null=True, upload_to="resumes/", verbose_name="Резюме (PDF)"
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="telegram",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Telegram (ссылка)"
            ),
        ),
    ]
