# Generated by Django 5.0.2 on 2025-05-06 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("positions", "0018_remove_candidate_current_position_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            # Создаем временную таблицу
            """
            CREATE TABLE positions_candidate_temp (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                full_name VARCHAR(255) NOT NULL,
                email VARCHAR(254) NULL,
                phone VARCHAR(30) NULL,
                telegram VARCHAR(100) NULL,
                desired_position_id INTEGER NULL REFERENCES positions_position(id),
                resume VARCHAR(100) NULL,
                notes TEXT NULL,
                created_at DATETIME NOT NULL,
                updated_at DATETIME NOT NULL
            );
            """,
            # Откат
            "DROP TABLE positions_candidate_temp;"
        ),
        migrations.RunSQL(
            # Копируем данные
            """
            INSERT INTO positions_candidate_temp (
                id, full_name, email, phone, telegram, desired_position_id,
                resume, notes, created_at, updated_at
            )
            SELECT 
                id, full_name, email, phone, telegram,
                CASE 
                    WHEN desired_position IS NULL THEN 2
                    ELSE (
                        SELECT id FROM positions_position 
                        WHERE name = desired_position 
                        LIMIT 1
                    )
                END,
                resume, notes, created_at, updated_at
            FROM positions_candidate;
            """,
            # Откат
            "DELETE FROM positions_candidate_temp;"
        ),
        migrations.RunSQL(
            # Удаляем старую таблицу
            "DROP TABLE positions_candidate;",
            # Откат
            """
            CREATE TABLE positions_candidate (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                full_name VARCHAR(255) NOT NULL,
                email VARCHAR(254) NULL,
                phone VARCHAR(30) NULL,
                telegram VARCHAR(100) NULL,
                desired_position VARCHAR(255) NULL,
                resume VARCHAR(100) NULL,
                notes TEXT NULL,
                created_at DATETIME NOT NULL,
                updated_at DATETIME NOT NULL
            );
            """
        ),
        migrations.RunSQL(
            # Переименовываем временную таблицу
            "ALTER TABLE positions_candidate_temp RENAME TO positions_candidate;",
            # Откат
            "ALTER TABLE positions_candidate RENAME TO positions_candidate_temp;"
        ),
    ]
