# Generated by Django 4.2.21 on 2025-05-15 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("positions", "0020_alter_candidate_desired_position_testanswer"),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="candidate_files/", verbose_name="Файл"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Загружено"),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="positions.candidate",
                        verbose_name="Кандидат",
                    ),
                ),
            ],
        ),
    ]
