# Generated by Django 4.2.21 on 2025-05-15 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("positions", "0021_candidatefile"),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название задачи"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="Дедлайн"),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Выполнено"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="positions.candidate",
                        verbose_name="Кандидат",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача по кандидату",
                "verbose_name_plural": "Задачи по кандидату",
            },
        ),
    ]
