# Generated by Django 4.2.21 on 2025-05-17 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("positions", "0026_create_vacancies_and_profiles"),
    ]

    operations = [
        migrations.CreateModel(
            name="VacancyGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Мин. ЗП",
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Макс. ЗП",
                    ),
                ),
                (
                    "requirements",
                    models.TextField(blank=True, verbose_name="Требования"),
                ),
                (
                    "responsibilities",
                    models.TextField(blank=True, verbose_name="Обязанности"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="positions.grade",
                        verbose_name="Грейд",
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="positions.vacancy",
                        verbose_name="Вакансия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Грейд вакансии",
                "verbose_name_plural": "Грейды вакансий",
                "ordering": ["grade__order"],
                "unique_together": {("vacancy", "grade")},
            },
        ),
    ]
