# Generated by Django 4.2.21 on 2025-05-17 11:18

from django.db import migrations

def populate_vacancy_grades(apps, schema_editor):
    Vacancy = apps.get_model('positions', 'Vacancy')
    Grade = apps.get_model('positions', 'Grade')
    VacancyGrade = apps.get_model('positions', 'VacancyGrade')
    
    # Получаем все грейды
    grades = Grade.objects.all().order_by('order')
    
    # Для каждой вакансии создаем записи для всех грейдов
    for vacancy in Vacancy.objects.all():
        for grade in grades:
            # Проверяем, есть ли уже запись для этого грейда
            if not VacancyGrade.objects.filter(vacancy=vacancy, grade=grade).exists():
                VacancyGrade.objects.create(
                    vacancy=vacancy,
                    grade=grade,
                    requirements=f'Требования для грейда {grade.name}',
                    responsibilities=f'Обязанности для грейда {grade.name}'
                )

def reverse_vacancy_grades(apps, schema_editor):
    VacancyGrade = apps.get_model('positions', 'VacancyGrade')
    VacancyGrade.objects.all().delete()

class Migration(migrations.Migration):
    dependencies = [
        ('positions', '0027_add_vacancy_grades'),
    ]

    operations = [
        migrations.RunPython(populate_vacancy_grades, reverse_vacancy_grades),
    ]
