# Generated by Django 4.2.21 on 2025-05-17 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("positions", "0028_populate_vacancy_grades"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancygrade",
            name="wishes",
            field=models.TextField(blank=True, verbose_name="Пожелания к кандидату"),
        ),
        migrations.AddField(
            model_name="vacancygrade",
            name="work_conditions",
            field=models.TextField(blank=True, verbose_name="Условия труда"),
        ),
        migrations.CreateModel(
            name="PositionProfileGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "general_description",
                    models.TextField(blank=True, verbose_name="Общее описание"),
                ),
                (
                    "hard_skills",
                    models.TextField(blank=True, verbose_name="Hard skills"),
                ),
                (
                    "hard_requirements",
                    models.TextField(
                        blank=True, verbose_name="Требования к hard skills"
                    ),
                ),
                (
                    "hard_level",
                    models.TextField(
                        blank=True, verbose_name="Уровень владения hard skills"
                    ),
                ),
                (
                    "soft_meta_skills",
                    models.TextField(blank=True, verbose_name="Soft & meta skills"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Пояснения")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="positions.grade",
                        verbose_name="Грейд",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_profiles",
                        to="positions.positionprofile",
                        verbose_name="Профиль должности",
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_grades",
                        to="positions.vacancy",
                        verbose_name="Вакансия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль по грейду",
                "verbose_name_plural": "Профили по грейдам",
                "ordering": ["grade__order"],
                "unique_together": {("vacancy", "grade", "profile")},
            },
        ),
    ]
