# Generated by Django 4.2.21 on 2025-05-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("positions", "0029_add_grade_tabs_and_profile_struct"),
    ]

    operations = [
        migrations.AddField(
            model_name="positionprofilegrade",
            name="salary_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Зарплата (до)",
            ),
        ),
        migrations.AddField(
            model_name="positionprofilegrade",
            name="salary_min",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Зарплата (от)",
            ),
        ),
        migrations.AddField(
            model_name="positionprofilegrade",
            name="supervisor",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Руководитель"
            ),
        ),
    ]
