# Generated by Django 4.2.21 on 2025-05-18 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orgstructure", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepartmentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="Тип отдела"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#2563eb", max_length=7, verbose_name="Цвет (HEX)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип отдела",
                "verbose_name_plural": "Типы отделов",
            },
        ),
        migrations.AddField(
            model_name="department",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="orgstructure.departmenttype",
                verbose_name="Тип отдела",
            ),
        ),
    ]
