# Generated by Django 4.2.21 on 2025-05-18 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orgstructure", "0002_departmenttype_department_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffmember",
            name="role",
            field=models.CharField(
                choices=[
                    ("employee", "Сотрудник"),
                    ("manager", "Руководитель"),
                    ("hr", "HR"),
                    ("director", "Директор"),
                    ("other", "Другое"),
                ],
                default="employee",
                max_length=32,
                verbose_name="Роль",
            ),
        ),
        migrations.CreateModel(
            name="StaffTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата события")),
                (
                    "from_position",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Была должность",
                    ),
                ),
                (
                    "to_position",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Стала должность",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("transfer", "Перевод"),
                            ("promotion", "Повышение"),
                            ("other", "Другое"),
                        ],
                        default="transfer",
                        max_length=32,
                        verbose_name="Тип события",
                    ),
                ),
                (
                    "from_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="orgstructure.department",
                        verbose_name="Из отдела",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers",
                        to="orgstructure.staffmember",
                        verbose_name="Сотрудник",
                    ),
                ),
                (
                    "to_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="orgstructure.department",
                        verbose_name="В отдел",
                    ),
                ),
            ],
            options={
                "verbose_name": "Перевод/повышение",
                "verbose_name_plural": "Переводы/повышения",
                "ordering": ["-date"],
            },
        ),
    ]
